name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [ubuntu-large]
    container:
      image: ghcr.io/cirruslabs/flutter:latest

    steps:
      - uses: actions/checkout@v4

      - run: flutter --version
      - run: flutter pub get
      - run: cd viam_example_app && flutter pub get

       # Verify formatting in all dart files
      - name: Verify formatting
        run: dart format --line-length=140 --set-exit-if-changed $(find ./lib -name "*.dart" -not -path "./lib/proto/*")

      - name: Analyze project source
        run: dart analyze

      # TODO: add tests
      # - name: Run tests
      #   run: flutter test
